trends = [
    {
        "hashtag":"pokemonportugal",
        "posts":4647,
        "trend":13.86,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbontravel",
        "posts":38204,
        "trend":12.26,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"editorskerala",
        "posts":28634,
        "trend":10.35,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"ronaldoskills",
        "posts":151964,
        "trend":9.74,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"cropk",
        "posts":23610,
        "trend":9.41,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugaltravel",
        "posts":561303,
        "trend":7.67,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portoportugal",
        "posts":506275,
        "trend":7.42,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"ronaldogoal",
        "posts":177259,
        "trend":7.33,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"madeiranatural",
        "posts":30982,
        "trend":6.17,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"algarveportugal",
        "posts":508767,
        "trend":6.13,
        "usage":{
            "count":5,
            "last":"2022-10-07T19:02:51+00:00"
        }
    },
    {
        "hashtag":"algarvecoast",
        "posts":151176,
        "trend":6.1,
        "usage":{
            "count":1,
            "last":"2022-10-01T18:03:24+00:00"
        }
    },
    {
        "hashtag":"algarvelovers",
        "posts":221125,
        "trend":5.98,
        "usage":{
            "count":1,
            "last":"2022-10-01T18:03:24+00:00"
        }
    },
    {
        "hashtag":"visitalgarve",
        "posts":252909,
        "trend":5.89,
        "usage":{
            "count":1,
            "last":"2022-10-01T18:03:24+00:00"
        }
    },
    {
        "hashtag":"exploreportugal",
        "posts":112315,
        "trend":5.73,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"melides",
        "posts":35364,
        "trend":5.63,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"apparelbrand",
        "posts":732449,
        "trend":5.53,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"leiria",
        "posts":517793,
        "trend":5.39,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"mafra",
        "posts":385031,
        "trend":5.35,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"benagilcave",
        "posts":48982,
        "trend":5.15,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portomoniz",
        "posts":61471,
        "trend":5.07,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"visitmadeira",
        "posts":618886,
        "trend":4.96,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"todosportugal",
        "posts":46994,
        "trend":4.96,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"visitlisboa",
        "posts":291840,
        "trend":4.88,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonfood",
        "posts":111337,
        "trend":4.83,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugallovers",
        "posts":630704,
        "trend":4.79,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"travelportugal",
        "posts":265646,
        "trend":4.73,
        "usage":{
            "count":9,
            "last":"2022-10-05T10:46:39+00:00"
        }
    },
    {
        "hashtag":"sintraportugal",
        "posts":247404,
        "trend":4.69,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonportugal",
        "posts":458665,
        "trend":4.67,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonphotographer",
        "posts":57210,
        "trend":4.65,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"clothingdesigner",
        "posts":473754,
        "trend":4.57,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonstreets",
        "posts":89901,
        "trend":4.54,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"azoresislands",
        "posts":364444,
        "trend":4.54,
        "usage":{
            "count":8,
            "last":"2022-10-04T20:02:22+00:00"
        }
    },
    {
        "hashtag":"portimao",
        "posts":387374,
        "trend":4.37,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"cr7ronaldo",
        "posts":110246,
        "trend":4.27,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"madeiralovers",
        "posts":338460,
        "trend":4.21,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"visitlisbon",
        "posts":448739,
        "trend":4.17,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"dourovalley",
        "posts":270529,
        "trend":4.03,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"visitporto",
        "posts":470364,
        "trend":3.99,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"azoreswhatelse",
        "posts":255926,
        "trend":3.94,
        "usage":{
            "count":9,
            "last":"2022-10-05T10:46:39+00:00"
        }
    },
    {
        "hashtag":"fatima",
        "posts":969272,
        "trend":3.93,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonlife",
        "posts":133700,
        "trend":3.87,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"familytravels",
        "posts":475588,
        "trend":3.86,
        "usage":{
            "count":1,
            "last":"2022-10-01T18:03:24+00:00"
        }
    },
    {
        "hashtag":"comporta",
        "posts":174576,
        "trend":3.73,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"tavira",
        "posts":263329,
        "trend":3.72,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"carvoeiro",
        "posts":141929,
        "trend":3.7,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"pasteldenata",
        "posts":238080,
        "trend":3.68,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"cr7fans",
        "posts":855778,
        "trend":3.68,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"funchal",
        "posts":847299,
        "trend":3.62,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"estoril",
        "posts":347595,
        "trend":3.55,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lagosportugal",
        "posts":225525,
        "trend":3.55,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonworld",
        "posts":109276,
        "trend":3.46,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"benagil",
        "posts":106095,
        "trend":3.33,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"nazare",
        "posts":520587,
        "trend":3.31,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"saomiguel",
        "posts":598251,
        "trend":3.31,
        "usage":{
            "count":8,
            "last":"2022-10-04T20:02:22+00:00"
        }
    },
    {
        "hashtag":"ericeira",
        "posts":528685,
        "trend":3.17,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"fearlessphotographer",
        "posts":826819,
        "trend":3.16,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lizbona",
        "posts":74566,
        "trend":3.15,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugalia",
        "posts":227293,
        "trend":3.14,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"albufeira",
        "posts":827273,
        "trend":3.04,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"cristianoronaldo7",
        "posts":721954,
        "trend":2.9,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"douro",
        "posts":818069,
        "trend":2.85,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugalwedding",
        "posts":111256,
        "trend":2.81,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisboacool",
        "posts":293862,
        "trend":2.69,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"designhotel",
        "posts":499913,
        "trend":2.69,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portwine",
        "posts":226354,
        "trend":2.65,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"douroriver",
        "posts":230263,
        "trend":2.62,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbona",
        "posts":691725,
        "trend":2.55,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"15aoburro",
        "posts":680655,
        "trend":2.45,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisbonlovers",
        "posts":885586,
        "trend":2.39,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"palaciodapena",
        "posts":140630,
        "trend":2.35,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lissabon",
        "posts":862980,
        "trend":2.31,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"peniche",
        "posts":547523,
        "trend":2.31,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lookslikefilmpt",
        "posts":45411,
        "trend":2.21,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"alfama",
        "posts":413247,
        "trend":2.15,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugal_gems",
        "posts":406073,
        "trend":2.11,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"penapalace",
        "posts":142532,
        "trend":2.03,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"sharing_portugal",
        "posts":945789,
        "trend":2.01,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"wonderlustportugal",
        "posts":474525,
        "trend":1.96,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugal_a_gramas",
        "posts":802448,
        "trend":1.9,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"loveportugal",
        "posts":200393,
        "trend":1.9,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"ilovemadeira",
        "posts":267987,
        "trend":1.88,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugal_places",
        "posts":618331,
        "trend":1.77,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"sagres",
        "posts":390437,
        "trend":1.75,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"cabodaroca",
        "posts":259904,
        "trend":1.72,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"super_lisboa",
        "posts":305025,
        "trend":1.69,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"lisboalive",
        "posts":696095,
        "trend":1.64,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"yourockphotographers",
        "posts":668646,
        "trend":1.5,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugalemperspectiva",
        "posts":716268,
        "trend":1.48,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugalovers",
        "posts":458005,
        "trend":1.47,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugal_lovers",
        "posts":918841,
        "trend":1.43,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugalemfiltros",
        "posts":484072,
        "trend":1.39,
        "usage":{
            "count":9,
            "last":"2022-10-05T10:46:39+00:00"
        }
    },
    {
        "hashtag":"click2inspire",
        "posts":748599,
        "trend":1.32,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"visual_square",
        "posts":991679,
        "trend":1.23,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"topportugalphoto",
        "posts":617293,
        "trend":1.22,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"freekick",
        "posts":935204,
        "trend":1.2,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"portugalalive",
        "posts":873585,
        "trend":1.11,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"igerslisboa",
        "posts":541278,
        "trend":1.04,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"loves_portugal",
        "posts":512062,
        "trend":0.95,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"toplisbonphoto",
        "posts":254490,
        "trend":0.69,
        "usage":{
            "count":0,
            "last":None
        }
    },
    {
        "hashtag":"faded_portugal",
        "posts":733895,
        "trend":0.37,
        "usage":{
            "count":0,
            "last":None
        }
    }
]